// Code generated by internal/gen. DO NOT EDIT.

// Package consumer12 reaches through to backend A's raw row — the coupling the
// backend A->B migration forces to change. One of N identical dependents; the
// coupled arm's forced-edit count is N. Fails to build under -tags swap because
// its own source names backend.OrderRowA / backend.FetchRawA.
package consumer12

import (
	"context"

	"github.com/verocorp/go-ddd/rationale/changeability/anchor/backend"
	"github.com/verocorp/go-ddd/rationale/changeability/anchor/orders"
)

// Use places an order, then reaches through to backend A's storage row.
func Use(ctx context.Context, c orders.Client) (backend.OrderRowA, error) {
	resp, err := c.PlaceOrder(ctx, orders.PlaceOrderRequest{CustomerID: "c12", SKUs: []string{"x"}})
	if err != nil {
		return backend.OrderRowA{}, err
	}
	return backend.FetchRawA(resp.OrderID), nil
}
