from alpha.adapters.runners.inline_keep_widget_relay import InlineKeepWidgetRelay as InlineKeepWidgetRelay
from alpha.adapters.runners.inline_register_widget_relay import InlineRegisterWidgetRelay as InlineRegisterWidgetRelay
