// Code generated by internal/gen. DO NOT EDIT.

// Package consumer01 is one dependent of the ordering context. It depends
// ONLY on orders.Client (the public boundary), so the backend A->B migration
// forces 0 edits on it. One of N identical dependents; the decoupled arm's
// forced-edit count stays 0 for any N.
package consumer01

import (
	"context"

	"github.com/verocorp/go-ddd/rationale/changeability/anchor/orders"
)

// Use exercises the public contract and nothing else.
func Use(ctx context.Context, c orders.Client) error {
	_, err := c.PlaceOrder(ctx, orders.PlaceOrderRequest{CustomerID: "c01", SKUs: []string{"x"}})
	return err
}
