// Code generated by internal/gen. DO NOT EDIT.

// Package consumer12 reaches the DOMAIN-EMITTED DTO (emit.Maneuver.ToResponse())
// and reads a raw wire field. The outward-format migration removes that field, so
// this dependent is forced to change. One of N identical dependents; the coupled
// arm's forced-edit count is N. Fails to build under -tags repv2 because its own
// source names ToResponse().BurnSeconds.
package consumer12

import "github.com/verocorp/go-ddd/rationale/changeability/nooutward/emit"

// Use reaches through the domain-emitted outward DTO to a wire-format field.
func Use(m emit.Maneuver) int64 {
	return m.ToResponse().BurnSeconds
}
