package campaign

import "fmt"

// CampaignID is the identity of a Campaign. Simple, single-value value
// object: flat constructor, native equality. It is generated by the
// application layer (the skill doesn't cover ID-generation strategy) and
// validated here as non-empty.
type CampaignID struct {
	value string
}

// NewCampaignID validates and constructs a CampaignID.
func NewCampaignID(value string) (CampaignID, error) {
	if value == "" {
		return CampaignID{}, fmt.Errorf("campaign id must not be empty")
	}
	return CampaignID{value: value}, nil
}

// MustNewCampaignID panics on invalid input; use only with known-valid
// literals (tests, package-level vars), never with runtime data.
func MustNewCampaignID(value string) CampaignID {
	id, err := NewCampaignID(value)
	if err != nil {
		panic(err)
	}
	return id
}

// String is the display form and the sole string accessor.
func (id CampaignID) String() string {
	return id.value
}
