from dataclasses import dataclass


@dataclass(frozen=True)
class CampaignID:
    """The identity of a Campaign. Simple, single-value value object: one
    field, validation in ``__post_init__``, value equality from ``frozen=True``.
    It is generated by the application layer (the skill doesn't cover
    ID-generation strategy) and validated here as non-empty.

    No ``MustCampaignID`` twin is needed: construction already raises on invalid
    input — Python's exception is the panic path Go's ``MustNew*`` provides. In
    tests, construct directly with known-valid literals.
    """

    value: str

    def __post_init__(self) -> None:
        if not self.value:
            raise ValueError("campaign id must not be empty")

    def __str__(self) -> str:
        return self.value
