from reports.domain.report import Decision as Decision
from reports.domain.report import Link as Link
from reports.domain.report import LinkSpec as LinkSpec
from reports.domain.report import LinkVerdict as LinkVerdict
from reports.domain.report import LinkVerdictSpec as LinkVerdictSpec
from reports.domain.report import LinkVerdicts as LinkVerdicts
from reports.domain.report import LinkVerdictsSpec as LinkVerdictsSpec
from reports.domain.report import Reason as Reason
from reports.domain.report import RecordedVerdict as RecordedVerdict
from reports.domain.report import RecordedVerdictSpec as RecordedVerdictSpec
from reports.domain.report import TargetURL as TargetURL
