// Code generated by internal/gen. DO NOT EDIT.

// Package consumer15 depends ONLY on orders.Client (the public boundary), so
// the backend A->B migration forces 0 edits on it. One of N identical dependents;
// the decoupled arm's forced-edit count stays 0 for any N.
package consumer15

import (
	"context"

	"github.com/verocorp/go-ddd/rationale/changeability/anchor/orders"
)

// Use exercises the public contract and nothing else.
func Use(ctx context.Context, c orders.Client) error {
	_, err := c.PlaceOrder(ctx, orders.PlaceOrderRequest{CustomerID: "c15", SKUs: []string{"x"}})
	return err
}
