// Code generated by internal/gen. DO NOT EDIT.

// Package consumer10 operates on the domain object's VALUE OBJECTS — never an
// outward representation. The outward-format migration forces 0 edits on it. One
// of N identical dependents; the decoupled arm's forced-edit count stays 0 for
// any N.
package consumer10

import "github.com/verocorp/go-ddd/rationale/changeability/nooutward/domain"

// Use reads the domain object through its value objects and nothing outward.
func Use(m domain.Maneuver) int64 {
	return m.Burn().Seconds()
}
