from scheduling.client.client import BeginBookingRequest as BeginBookingRequest
from scheduling.client.client import BeginBookingResponse as BeginBookingResponse
from scheduling.client.client import Booking as Booking
from scheduling.client.client import ChooseSlotRequest as ChooseSlotRequest
from scheduling.client.client import ChooseSlotResponse as ChooseSlotResponse
from scheduling.client.client import ConfirmBookingRequest as ConfirmBookingRequest
from scheduling.client.client import ConfirmBookingResponse as ConfirmBookingResponse
from scheduling.client.client import GetBookingRequest as GetBookingRequest
from scheduling.client.client import GetBookingResponse as GetBookingResponse
from scheduling.client.client import ProvideNameRequest as ProvideNameRequest
from scheduling.client.client import ProvideNameResponse as ProvideNameResponse
from scheduling.client.client import SchedulingClient as SchedulingClient
